### ISSUE TITLE
Final group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by didierganthier** [didierganthier/rent-a-car-backend#9]
## Final group capstone: set up your Kanban board
The project link can be found [here](https://github.com/users/didierganthier/projects/7/views/1)

## Team Members
- @didierganthier 
- @Shedrack-Sunday 
- @Efiamotu-1 

## Kanban Preview
![Screenshot 2023-02-24 at 10 06 15](https://user-images.githubusercontent.com/45739963/221212535-953fdfff-0783-471e-9260-59a26c29f358.png)

**Comment by Meltrust** [comment]
Hi @didierganthier,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks are assigned✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] According to the [project requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md):

![image](https://user-images.githubusercontent.com/57421823/221221794-b4f488e3-d6bf-4594-a0da-63e31f302117.png)

However, at the time of this review, these are the paintings:

@Shedrack-Sunday 21
@Efiamotu-1 27
@didierganthier 23

- As you can notice, @Efiamotu-1 has 6 points more than @Shedrack-Sunday. 
In order to meet this requirement, kindly move the pointings so no team member has more or less than 5 points than any other member of the team.

Tip:  Just move the pointings and/or reassign some tasks so no team member has more than 5 points than anyone else in the team. 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
Hi @didierganthier,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
